version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running pre-build scripts...

  build:
    commands:
      - echo Building the application...
      - npm run build

  post_build:
    commands:
      - echo Zipping application for Elastic Beanstalk deployment...
      - zip -r nodejs-app.zip * .[^.]*

artifacts:
  files:
    - nodejs-app.zip

  discard-paths: yes
